[Application Options]
noseedbackup=true
restlisten=0.0.0.0:8080
rpclisten=0.0.0.0:10009
listen=0.0.0.0:9735
tlsextraip=0.0.0.0
tlsextradomain=lnd-bob
debuglevel=error

[Bitcoin]
bitcoin.active=true
bitcoin.regtest=true
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpchost=bitcoind:18443
bitcoind.rpcuser=test
bitcoind.rpcpass=test
bitcoind.zmqpubrawblock=tcp://bitcoind:28332
bitcoind.zmqpubrawtx=tcp://bitcoind:28333
